# Generated by Django 6.0.7 on 2026-07-20 22:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=512)),
                ('file_path', models.CharField(max_length=1024)),
                ('checksum', models.CharField(db_index=True, max_length=64, unique=True)),
                ('mime_type', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('extraction_method', models.CharField(blank=True, choices=[('direct_text', 'Direct text extraction'), ('ocr', 'OCR')], max_length=16, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
